# Projeto 2 - Como pegar dados em sites e automatizar a criação da carteira

## Passo a passo

 - 1 - definir o navegador
 - 2 - importar os módulos e bibliotecas
 - 3 - entender como funcionam requisições na internet
 - 4 - entender como sites funcionam
 - 5 - conhecer e mapear o processo de coleta de dados no site Fundamentus
 - 6 - ler a tabela de dados
 - 7 - construir a tabela final

### 1 - definir o navegador

neste caso, utilizarei o Google Chrome

### 2 - importar os módulos e bibliotecas

In [41]:
# !pip install selenium

In [42]:
# !pip install webdriver-manager

In [43]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

### 3 - entender como funcionam requisições na internet

In [44]:
# driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))
driver = webdriver.Chrome('../chromedriver.exe')

url = 'https://www.fundamentus.com.br/resultado.php'

driver.get(url)

C:\Users\bruno.dorea.SPREADTEC\AppData\Local\Temp\ipykernel_13004\1247649361.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('../chromedriver.exe')

### 4 - entender como sites funcionam

### 5 - conhecer e mapear o processo de coleta de dados no site Fundamentus

### 6 - ler a tabela de dados

In [45]:
local_tabela = '/html/body/div[1]/div[2]/table'

elemento = driver.find_element("xpath", local_tabela)

html_tabela = elemento.get_attribute('outerHTML')

tabela = pd.read_html(str(html_tabela), thousands = '.', decimal = ',')[0]

tabela

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
1,MNSA4,0.47,0.00,0.00,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"-208,15%","-362,66%",3.63,"-13,50%","145,70%",0.0,-9.105000e+06,-6.52,"-41,11%"
2,PORP4,2.40,0.00,0.00,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-2,08%",0.0,2.239900e+07,0.00,"13,66%"
3,POPR4,10.17,0.00,0.00,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"8,66%","5,65%",1.08,"15,25%","19,93%",0.0,5.458030e+08,0.82,"30,93%"
4,IVTT3,0.00,0.00,0.00,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-0,40%",0.0,1.083050e+09,0.00,"20,67%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,PRBC4,14.54,502.29,40.26,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","8,02%",0.0,1.176410e+09,0.00,"-6,01%"
983,UBBR4,7.49,610.27,1.99,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
984,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
985,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.000,0.00,0.0,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
986,SQIA3,26.65,2672.35,3.66,3.569,"0,21%",1.461,26.34,42.1,-3.63,...,16.08,"8,48%","0,45%",1.44,"4,04%","0,14%",25416100.0,6.397490e+08,0.67,"46,25%"

### 7 - construir a tabela final

In [46]:
tabela = tabela.set_index("Papel")
tabela = tabela[['Cotação', 'EV/EBIT', 'ROIC', 'Liq.2meses']]

tabela

        Cotação  EV/EBIT     ROIC  Liq.2meses
Papel
CSTB4    147.69      0.0   22,40%         0.0
MNSA4      0.47      0.0  -13,50%         0.0
PORP4      2.40      0.0    0,00%         0.0
POPR4     10.17      0.0   15,25%         0.0
IVTT3      0.00      0.0    0,00%         0.0
...         ...      ...      ...         ...
PRBC4     14.54      0.0    0,00%         0.0
UBBR4      7.49      0.0    0,00%         0.0
UBBR11    14.75      0.0    0,00%         0.0
UBBR3     18.00      0.0    0,00%         0.0
SQIA3     26.65     45.9    4,04%  25416100.0

[987 rows x 4 columns]

In [47]:
# transformar texto em numero

tabela['ROIC'] = tabela['ROIC'].str.replace('%', '')
tabela['ROIC'] = tabela['ROIC'].str.replace('.', '')
tabela['ROIC'] = tabela['ROIC'].str.replace(',', '.')
tabela['ROIC'] = tabela['ROIC'].astype(float)

tabela

        Cotação  EV/EBIT   ROIC  Liq.2meses
Papel
CSTB4    147.69      0.0  22.40         0.0
MNSA4      0.47      0.0 -13.50         0.0
PORP4      2.40      0.0   0.00         0.0
POPR4     10.17      0.0  15.25         0.0
IVTT3      0.00      0.0   0.00         0.0
...         ...      ...    ...         ...
PRBC4     14.54      0.0   0.00         0.0
UBBR4      7.49      0.0   0.00         0.0
UBBR11    14.75      0.0   0.00         0.0
UBBR3     18.00      0.0   0.00         0.0
SQIA3     26.65     45.9   4.04  25416100.0

[987 rows x 4 columns]

In [48]:
# criando filtros e os rankings

tabela = tabela[tabela['Liq.2meses'] > 1000000]

tabela

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     3.90     5.21  13.95   20118000.0
MEGA3    10.65    25.10   3.66    8310680.0
LWSA3     6.54    43.11   2.03   51831100.0
CBAV3     4.28    87.16   0.53   35498100.0
MYPK3    14.76     9.12   6.73   21019000.0
...        ...      ...    ...          ...
CRFB3    11.26     8.72   6.66  121111000.0
YDUQ3    22.25    14.88   8.99  116395000.0
CEAB3     6.17     7.69   5.28   26425400.0
PTBL3     6.99    11.27   7.36   10911000.0
SQIA3    26.65    45.90   4.04   25416100.0

[244 rows x 4 columns]

In [49]:
tabela = tabela[tabela['EV/EBIT'] > 0]
tabela = tabela[tabela['ROIC'] > 0]

tabela

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     3.90     5.21  13.95   20118000.0
MEGA3    10.65    25.10   3.66    8310680.0
LWSA3     6.54    43.11   2.03   51831100.0
CBAV3     4.28    87.16   0.53   35498100.0
MYPK3    14.76     9.12   6.73   21019000.0
...        ...      ...    ...          ...
CRFB3    11.26     8.72   6.66  121111000.0
YDUQ3    22.25    14.88   8.99  116395000.0
CEAB3     6.17     7.69   5.28   26425400.0
PTBL3     6.99    11.27   7.36   10911000.0
SQIA3    26.65    45.90   4.04   25416100.0

[197 rows x 4 columns]

In [51]:
tabela['ranking_ev_ebit'] = tabela['EV/EBIT'].rank(ascending = True)
tabela['ranking_roic'] = tabela['ROIC'].rank(ascending = False)
tabela['ranking_final'] = tabela['ranking_ev_ebit'] + tabela['ranking_roic']

tabela

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_final
Papel,,,,,,,
QUAL3,3.90,5.21,13.95,20118000.0,26.0,64.0,90.0
MEGA3,10.65,25.10,3.66,8310680.0,178.0,166.0,344.0
LWSA3,6.54,43.11,2.03,51831100.0,186.0,184.0,370.0
CBAV3,4.28,87.16,0.53,35498100.0,192.0,194.0,386.0
MYPK3,14.76,9.12,6.73,21019000.0,83.5,132.0,215.5
...,...,...,...,...,...,...,...
CRFB3,11.26,8.72,6.66,121111000.0,81.0,133.0,214.0
YDUQ3,22.25,14.88,8.99,116395000.0,143.0,105.0,248.0
CEAB3,6.17,7.69,5.28,26425400.0,67.0,152.0,219.0
PTBL3,6.99,11.27,7.36,10911000.0,111.0,129.0,240.0
SQIA3,26.65,45.90,4.04,25416100.0,187.0,162.0,349.0

In [52]:
tabela = tabela.sort_values('ranking_final')

tabela.head(10)

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_ev_ebit,ranking_roic,ranking_final
Papel,,,,,,,
PSSA3,27.20,0.25,60.76,5.820690e+07,1.0,1.0,2.0
PETR4,31.44,2.40,28.95,1.606800e+09,4.0,10.5,14.5
PETR3,34.29,2.55,28.95,4.393320e+08,5.0,10.5,15.5
KEPL3,10.00,4.41,43.61,1.494980e+07,14.0,2.0,16.0
UNIP3,70.51,4.43,38.68,1.005490e+06,15.0,3.5,18.5
WIZC3,5.99,2.23,24.18,4.427250e+06,3.0,17.0,20.0
FESA4,43.02,4.05,25.57,9.707320e+06,8.0,15.0,23.0
UNIP6,75.41,4.74,38.68,1.714850e+07,21.0,3.5,24.5
CMIN3,4.05,4.56,28.49,2.938640e+07,19.0,12.0,31.0
VLID3,16.67,4.10,20.64,6.233610e+06,9.0,23.0,32.0